# Generated by Django 6.0.7 on 2026-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalDosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('morning_time', models.TimeField(blank=True, null=True)),
                ('morning_additive', models.FloatField(blank=True, null=True)),
                ('morning_fuel_qty', models.FloatField(blank=True, null=True)),
                ('evening_time', models.TimeField(blank=True, null=True)),
                ('evening_additive', models.FloatField(blank=True, null=True)),
                ('evening_fuel_qty', models.FloatField(blank=True, null=True)),
                ('total_additive', models.FloatField(blank=True, null=True)),
                ('total_fuel_qty', models.FloatField(blank=True, null=True)),
                ('chemical_rob', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['vessel', 'date'],
                'constraints': [models.UniqueConstraint(fields=('vessel', 'date'), name='unique_chemical_dosing')],
            },
        ),
        migrations.CreateModel(
            name='ChemicalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('fuel_load', models.FloatField(blank=True, null=True)),
                ('fuel_inlet', models.FloatField(blank=True, null=True)),
                ('fuel_outlet', models.FloatField(blank=True, null=True)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('power', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vessel', 'timestamp'],
                'constraints': [models.UniqueConstraint(fields=('vessel', 'timestamp'), name='unique_chemical_measurement')],
            },
        ),
    ]
