# Generated by Django 6.0.7 on 2026-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=100)),
                ('import_type', models.CharField(choices=[('Measurement', 'Measurement'), ('Dosing Log', 'Dosing Log')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('new_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
