# Generated by Django 6.0.7 on 2026-08-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0002_chemicalimporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicaldosing',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosing_records', to='chemical_analysis.chemicalimporthistory'),
        ),
        migrations.AddField(
            model_name='chemicalmeasurement',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='chemical_analysis.chemicalimporthistory'),
        ),
    ]
