# Generated by Django 6.0.7 on 2026-08-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0003_chemicaldosing_import_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalmeasurement',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_records', to='chemical_analysis.chemicalimporthistory'),
        ),
    ]
