# Generated by Django 6.0.7 on 2026-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0004_alter_chemicalmeasurement_import_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicaldosing',
            name='voyage',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=50),
        ),
    ]
