# Generated by Django 6.0.7 on 2026-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analysis', '0005_chemicaldosing_voyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalmeasurement',
            name='voyage',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=50),
        ),
    ]
