# Generated by Django 6.0.7 on 2026-08-28 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(choices=[('Laden', 'Laden'), ('Ballast', 'Ballast')], max_length=20)),
                ('departure', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VoyageObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_time', models.DateTimeField()),
                ('speed', models.FloatField(help_text='Reported STW in knots')),
                ('consumption', models.FloatField(help_text='ME Consumption in MT/day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scoc_monitoring.voyageleg')),
            ],
            options={
                'ordering': ['reported_time'],
                'constraints': [models.UniqueConstraint(fields=('leg', 'reported_time'), name='unique_leg_observation_time')],
            },
        ),
    ]
