# Generated by Django 6.0.7 on 2026-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageleg',
            name='average_consumption',
            field=models.FloatField(blank=True, help_text='Average ME consumption in MT/day', null=True),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='average_speed',
            field=models.FloatField(blank=True, help_text='Average reported speed in knots', null=True),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='observation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='target_consumption',
            field=models.FloatField(default=0, help_text='Target ME consumption in MT/day'),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='target_speed',
            field=models.FloatField(default=0, help_text='Target speed in knots'),
        ),
    ]
