# Generated by Django 6.0.7 on 2026-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0002_voyageleg_average_consumption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyageleg',
            options={'ordering': ['start_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='voyageobservation',
            options={'ordering': ['reported_time', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='voyageobservation',
            name='unique_leg_observation_time',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='observation_count',
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='distance_to_go',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='cylinder_oil_consumption_l',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='distance_to_go',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='duration_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='hsfo_rob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='load_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='lsfo_rob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='mgo_rob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='power_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='running_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='scoc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='average_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='average_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='departure',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='load_type',
            field=models.CharField(choices=[('Laden', 'Laden'), ('Ballast', 'Ballast')], default='Laden', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='target_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='target_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageobservation',
            name='consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyageobservation',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='voyageobservation',
            constraint=models.UniqueConstraint(fields=('leg', 'reported_time'), name='unique_observation_per_leg_time'),
        ),
    ]
