# Generated by Django 6.0.7 on 2026-08-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0003_alter_voyageleg_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageleg',
            name='voyage_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='source_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='load_type',
            field=models.CharField(choices=[('Laden', 'Laden'), ('Ballast', 'Ballast'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
