# Generated by Django 6.0.7 on 2026-09-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0004_voyageleg_voyage_reference_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voyageobservation',
            name='unique_observation_per_leg_time',
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='observation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='source_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='voyage_route',
            field=models.CharField(blank=True, default='', help_text='Example: Singapore → Krishnapatnam', max_length=255),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='course',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='current',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='distance_run',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='engine_load_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='engine_power_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='eta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='hsfo_consumption_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='hsfo_rob_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='lsfo_consumption_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='lsmgo_consumption_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='lsmgo_rob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='lsmgo_rob_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='position',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='shaft_power_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='slip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='swell',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='vessel_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='voyageobservation',
            name='wind',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='load_type',
            field=models.CharField(choices=[('LADEN', 'Laden'), ('BALLAST', 'Ballast'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='voyageobservation',
            constraint=models.UniqueConstraint(fields=('leg', 'reported_time'), name='unique_voyage_observation_time'),
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='mgo_rob',
        ),
    ]
