# Generated by Django 6.0.7 on 2026-09-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0005_remove_voyageobservation_unique_observation_per_leg_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyageleg',
            name='voyage_reference',
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='vessel_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
