# Generated by Django 6.0.7 on 2026-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0006_remove_voyageleg_voyage_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyageleg',
            options={'ordering': ['vessel_name', 'start_date', 'id']},
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='voyage_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
