# Generated by Django 5.2.5 on 2026-09-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoc_monitoring', '0007_alter_voyageleg_options_voyageleg_voyage_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyageleg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voyageobservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
