# Generated by Django 5.2.17 on 2026-09-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_vessel_scoc_active'),
        ('scoc_monitoring', '0008_alter_voyageleg_id_alter_voyageobservation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='voyageleg',
            options={'ordering': ['start_date', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='voyageobservation',
            name='unique_voyage_observation_time',
        ),
        migrations.RenameField(
            model_name='voyageobservation',
            old_name='course',
            new_name='mgo_rob',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='observation_count',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='source_message',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='vessel_name',
        ),
        migrations.RemoveField(
            model_name='voyageleg',
            name='voyage_route',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='current',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='distance_run',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='engine_load_percent',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='engine_power_kw',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='hsfo_consumption_mt',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='hsfo_rob_mt',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='lsfo_consumption_mt',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='lsmgo_consumption_mt',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='lsmgo_rob',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='lsmgo_rob_mt',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='position',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='shaft_power_kw',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='swell',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='vessel_name',
        ),
        migrations.RemoveField(
            model_name='voyageobservation',
            name='wind',
        ),
        migrations.AddField(
            model_name='voyageleg',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voyage_legs', to='inspections.vessel'),
        ),
        migrations.AlterField(
            model_name='voyageleg',
            name='load_type',
            field=models.CharField(choices=[('Laden', 'Laden'), ('Ballast', 'Ballast'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='voyageobservation',
            constraint=models.UniqueConstraint(fields=('leg', 'reported_time'), name='unique_observation_per_leg_time'),
        ),
    ]
