# Generated by Django 6.0.7 on 2026-08-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetisUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(blank=True, max_length=50)),
                ('vessel_type', models.CharField(blank=True, max_length=100)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_hours', models.FloatField(default=0)),
                ('total_fuel_tons', models.FloatField(default=0)),
                ('average_sfoc', models.FloatField(default=0)),
                ('average_load', models.FloatField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('co2_tons', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='Unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fuel.metisupload')),
            ],
        ),
        migrations.AddField(
            model_name='metisupload',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.vessel'),
        ),
    ]
