# Generated by Django 6.0.7 on 2026-08-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelperformance',
            options={'verbose_name': 'Fuel Performance', 'verbose_name_plural': '⛽ Fuel Performance Results'},
        ),
        migrations.AlterModelOptions(
            name='metisupload',
            options={'verbose_name': 'METIS Upload', 'verbose_name_plural': '📂 METIS Data Uploads'},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'verbose_name': 'Vessel', 'verbose_name_plural': '🚢 Vessels'},
        ),
    ]
