# Generated by Django 5.2.16 on 2026-07-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=20, unique=True)),
                ('inspected_item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_no', models.CharField(max_length=20, unique=True)),
                ('port', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('inspector', models.CharField(max_length=100)),
                ('validity_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_description', models.TextField()),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='inspections.checklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspections.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.vessel'),
        ),
    ]
