# Generated by Django 5.2.16 on 2026-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inspectionfinding',
            constraint=models.UniqueConstraint(fields=('inspection', 'checklist_item'), name='unique_checklist_per_inspection'),
        ),
    ]
