# Generated by Django 5.2.5 on 2026-09-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspectionfinding_unique_checklist_per_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='scoc_active',
            field=models.BooleanField(default=False),
        ),
    ]
