# Generated by Django 6.0.7 on 2026-09-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_vessel_scoc_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightShipRegisterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('high_risk', models.PositiveIntegerField(default=0)),
                ('medium_risk', models.PositiveIntegerField(default=0)),
                ('low_risk', models.PositiveIntegerField(default=0)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('severity_score', models.PositiveIntegerField(default=0)),
                ('validity_months', models.PositiveIntegerField(default=0)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rightship_register_records', to='inspections.vessel')),
            ],
            options={
                'ordering': ['source_row'],
                'constraints': [models.UniqueConstraint(fields=('vessel', 'inspection_date'), name='unique_rightship_register_vessel_date')],
            },
        ),
    ]
